version: '3.7'

services:
  redis_image:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
  db:
    container_name: pg_containers
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: helpTrader
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_containers
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"